// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvWqtooPz7PhluQQeSvJDZkYBFV0cfnSc',
    appId: '1:688130413209:web:36ac6a79c4ca10fc435e08',
    messagingSenderId: '688130413209',
    projectId: 'crudibasico',
    authDomain: 'crudibasico.firebaseapp.com',
    storageBucket: 'crudibasico.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJiQyTrhreJRnQWN737XL1oFk-oR7fSw',
    appId: '1:688130413209:android:4f355ad9482b57fa435e08',
    messagingSenderId: '688130413209',
    projectId: 'crudibasico',
    storageBucket: 'crudibasico.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4mSjkXQoyE7LiopuiUXhaUxymsqNKpKw',
    appId: '1:688130413209:ios:8a48077b402848cf435e08',
    messagingSenderId: '688130413209',
    projectId: 'crudibasico',
    storageBucket: 'crudibasico.appspot.com',
    iosBundleId: 'com.example.crudbasico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4mSjkXQoyE7LiopuiUXhaUxymsqNKpKw',
    appId: '1:688130413209:ios:d8360aede278c89b435e08',
    messagingSenderId: '688130413209',
    projectId: 'crudibasico',
    storageBucket: 'crudibasico.appspot.com',
    iosBundleId: 'com.example.crudbasico.RunnerTests',
  );
}
